import React from 'react';
import { Pressable, StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { useTheme } from './theme';
export function Screen({ children }: { children?: React.ReactNode }) { const { colors } = useTheme(); return <View style={[styles.screen, { backgroundColor: colors.bg }]}>{children}</View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: StyleProp<ViewStyle> }) { const { colors } = useTheme(); return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, style]}>{children}</View>; }
export function SectionTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { const { colors } = useTheme(); return <View style={styles.sectionTitle}><Text style={[styles.sectionText, { color: colors.text }]}>{title}</Text>{action && <Pressable onPress={onAction}><Text style={{ color: colors.accent, fontWeight: '700' }}>{action}</Text></Pressable>}</View>; }
export function Badge({ label, tone = 'neutral' }: { label: string; tone?: 'neutral' | 'good' | 'warning' | 'danger' }) { const { colors } = useTheme(); const color = tone === 'good' ? colors.positive : tone === 'warning' ? colors.warning : tone === 'danger' ? colors.danger : colors.accent; return <View style={[styles.badge, { backgroundColor: color + '18' }]}><Text style={{ color, fontSize: 11, fontWeight: '800', letterSpacing: .4 }}>{label}</Text></View>; }
export function ListRow({ title, detail, trailing, onPress }: { title: string; detail?: string; trailing?: React.ReactNode; onPress?: () => void }) { const { colors } = useTheme(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.row, pressed && { opacity: .66 }]}><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.text }]}>{title}</Text>{detail && <Text style={{ color: colors.muted, marginTop: 3, fontSize: 13 }}>{detail}</Text>}</View>{trailing ?? <Text style={{ color: colors.muted, fontSize: 20 }}>›</Text>}</Pressable>; }
export const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingBottom: 32 }, card: { borderWidth: 1, borderRadius: 18, padding: 16 }, sectionTitle: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 25, marginBottom: 11 }, sectionText: { fontSize: 17, fontWeight: '800', letterSpacing: -.2 }, badge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 7 }, row: { minHeight: 63, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#DDE3ED' }, rowTitle: { fontSize: 15, fontWeight: '700' } });
