import React from 'react';
import { Pressable, StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from './theme';
export function Screen({ children }: { children?: React.ReactNode }) { const { colors } = useTheme(); return <SafeAreaView edges={['top', 'left', 'right']} style={[styles.screen, { backgroundColor: colors.bg }]}>{children}</SafeAreaView>; }
export function Card({ children, style }: { children: React.ReactNode; style?: StyleProp<ViewStyle> }) { const { colors } = useTheme(); return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, style]}>{children}</View>; }
export function SectionTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { const { colors } = useTheme(); return <View style={styles.sectionTitle}><Text style={[styles.sectionText, { color: colors.text }]}>{title}</Text>{action && <Pressable accessibilityRole="button" accessibilityLabel={`${action}: ${title}`} hitSlop={8} onPress={onAction}><Text style={{ color: colors.accent, fontWeight: '700' }}>{action}</Text></Pressable>}</View>; }
export function Badge({ label, tone = 'neutral' }: { label: string; tone?: 'neutral' | 'good' | 'warning' | 'danger' }) { const { colors } = useTheme(); const color = tone === 'good' ? colors.positive : tone === 'warning' ? colors.warning : tone === 'danger' ? colors.danger : colors.accent; return <View style={[styles.badge, { backgroundColor: color + '18' }]}><Text style={{ color, fontSize: 11, fontWeight: '800', letterSpacing: .4 }}>{label}</Text></View>; }
export function ListRow({ title, detail, trailing, onPress }: { title: string; detail?: string; trailing?: React.ReactNode; onPress?: () => void }) { const { colors } = useTheme(); return <Pressable accessibilityRole={onPress ? 'button' : undefined} accessibilityLabel={detail ? `${title}. ${detail}` : title} onPress={onPress} style={({ pressed }) => [styles.row, { borderBottomColor: colors.border }, pressed && onPress && { opacity: .66 }]}><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.text }]}>{title}</Text>{detail && <Text style={{ color: colors.muted, marginTop: 3, fontSize: 13, lineHeight: 18 }}>{detail}</Text>}</View>{trailing ?? (onPress ? <Text style={{ color: colors.muted, fontSize: 20 }}>›</Text> : null)}</Pressable>; }
export function LoadingState({ label = 'Loading your student workspace…' }: { label?: string }) { const { colors } = useTheme(); return <Screen><View style={styles.centerState}><View style={[styles.skeleton, { backgroundColor: colors.elevated, width: '52%' }]} /><View style={[styles.skeleton, { backgroundColor: colors.elevated, width: '88%', marginTop: 12 }]} /><View style={[styles.skeleton, { backgroundColor: colors.elevated, width: '88%', height: 116, marginTop: 22 }]} /><Text style={{ color: colors.muted, marginTop: 22 }}>{label}</Text></View></Screen>; }
export function ErrorState({ title = 'This section couldn’t be refreshed.', detail = 'Check your connection and try again.', onRetry }: { title?: string; detail?: string; onRetry?: () => void }) { const { colors } = useTheme(); return <Screen><View style={styles.centerState}><Text style={[styles.stateTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.stateDetail, { color: colors.muted }]}>{detail}</Text>{onRetry && <Pressable accessibilityRole="button" onPress={onRetry} style={[styles.retry, { backgroundColor: colors.accent }]}><Text style={styles.retryText}>Try again</Text></Pressable>}</View></Screen>; }
export function EmptyState({ title, detail }: { title: string; detail: string }) { const { colors } = useTheme(); return <View style={styles.empty}><Text style={[styles.stateTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.stateDetail, { color: colors.muted }]}>{detail}</Text></View>; }
export const styles = StyleSheet.create({ screen: { flex: 1 }, content: { paddingHorizontal: 20, paddingBottom: 32 }, card: { borderWidth: 1, borderRadius: 18, padding: 16 }, sectionTitle: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 25, marginBottom: 11 }, sectionText: { fontSize: 17, fontWeight: '800', letterSpacing: -.2 }, badge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 7 }, row: { minHeight: 63, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth }, rowTitle: { fontSize: 15, fontWeight: '700' }, centerState: { flex: 1, paddingHorizontal: 28, alignItems: 'center', justifyContent: 'center' }, skeleton: { height: 16, borderRadius: 8, alignSelf: 'flex-start' }, stateTitle: { textAlign: 'center', fontSize: 18, fontWeight: '800' }, stateDetail: { textAlign: 'center', lineHeight: 21, marginTop: 8 }, retry: { minHeight: 46, paddingHorizontal: 18, borderRadius: 12, justifyContent: 'center', marginTop: 18 }, retryText: { color: '#FFF', fontWeight: '800' }, empty: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 20 } });
