from pydantic import BaseModel
from typing import Protocol

class Profile(BaseModel):
    name: str
    register_number: str
    programme: str
    semester: int

class StudentDataProvider(Protocol):
    async def get_profile(self) -> Profile: ...
    async def get_attendance(self) -> dict: ...
    async def get_timetable(self) -> list[dict]: ...
    async def get_marks(self) -> list[dict]: ...
    async def get_exams(self) -> list[dict]: ...
    async def get_fees(self) -> dict: ...
    async def get_notifications(self) -> list[dict]: ...
